repos:
  - repo: local
    hooks:
      - id: lint
        name: ESLint
        entry: bash -c 'pnpm lint'
        language: system
        files: \.(ts|svelte)$
        pass_filenames: false

      - id: check
        name: Svelte check
        entry: bash -c 'pnpm check'
        language: system
        files: \.(ts|svelte)$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: detect-private-key
